# Generated by Django 4.2 on 2023-04-03 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('body', models.CharField(max_length=1000)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='project_priority',
            fields=[
                ('current_priority', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('count_tot_project', models.IntegerField()),
                ('employees_available', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('task_name', models.CharField(max_length=100)),
                ('date_added', models.DateField(auto_now=True)),
                ('task_description', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'emp_tasks',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Fname', models.CharField(max_length=20)),
                ('Lname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('project_name', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('hourly_rate', models.IntegerField(null=True)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.client')),
                ('pm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('log_ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(auto_now_add=True, max_length=50)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('work_completed', models.CharField(max_length=1000)),
                ('employee_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.user')),
                ('project_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.project')),
                ('task_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.task')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.comment')),
            ],
            options={
                'verbose_name_plural': 'myentries',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_Fname', models.CharField(max_length=100, null=True)),
                ('id', models.AutoField(default=1000, primary_key=True, serialize=False)),
                ('emp_Lname', models.CharField(max_length=100, null=True)),
                ('emp_address', models.CharField(max_length=100, null=True)),
                ('emp_phone', models.IntegerField(null=True)),
                ('task_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_app.task')),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('cost_ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('Price_per', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('tot_cost', models.IntegerField()),
                ('project_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.project')),
            ],
        ),
    ]
