# Generated by Django 4.2 on 2023-04-04 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_ID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_ID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='cost',
            old_name='cost_ID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='hour',
            old_name='log_ID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_ID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_ID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_ID',
            new_name='ID',
        ),
    ]
