# Generated by Django 4.2 on 2023-04-04 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_rename_client_id_client_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='cost',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='hour',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='ID',
            new_name='id',
        ),
    ]
