# Generated by Django 4.2 on 2023-04-16 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_rename_id_client_id_rename_id_comment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_app.client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pm_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_app.user'),
        ),
    ]
