# Generated by Django 4.2 on 2023-04-23 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0007_team_delete_project_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_app.project'),
        ),
    ]
